import "../../app/globals.css";
import { headers } from 'next/headers';
import { Analytics } from "@vercel/analytics/react";

const tools = {
  en: {
    calorie: { name: "Calorie Calculator - BMR, TDEE, BMI & Macro Calculator - Free Online", desc: "Free online calorie calculator: calculate BMR (Basal Metabolic Rate), TDEE (Total Daily Energy Expenditure), BMI, and macronutrients (protein, carbs, fat) for weight loss, weight maintenance or muscle gain. Uses Mifflin-St Jeor equation. Mac OS 9 retro style.", cat: "HealthApplication, Nutrition" },
    bmi: { name: "BMI Calculator - Body Mass Index Calculator - Free Online BMI Chart", desc: "Free online BMI calculator: calculate your Body Mass Index (BMI) using height and weight. Check your BMI category — underweight, normal, overweight, or obese. See healthy weight range and BMI chart. Color-coded gauge. Mac OS 9 retro style.", cat: "HealthApplication" },
    convert: { name: "Unit Converter - Length, Weight, Temperature, Volume, Area Converter", desc: "Free online unit converter: convert length (cm to inches, meters to feet, miles to km), weight (kg to lbs, ounces to grams), temperature (Celsius to Fahrenheit), volume (liters to gallons), area, speed, pressure. Easy bidirectional conversion.", cat: "UtilitiesApplication" },
    date: { name: "Date Calculator - Days Between Dates, D-Day Countdown, Age Calculator", desc: "Free online date calculator: calculate days between dates, D-Day countdown, add or subtract days from a date, calculate exact age in years months days, find anniversaries and due dates.", cat: "UtilitiesApplication" },
    photo: { name: "Photo Editor - Resize Image, Crop Photo, Compress JPEG PNG WebP Online Free", desc: "Free online photo editor: resize images, crop photos, compress JPEG PNG and WebP files. Reduce image file size without losing quality. Convert between image formats. Drag and drop, no upload required.", cat: "MultimediaApplication" },
    qr: { name: "QR Code Generator - Free Online QR Code Maker - Create QR Codes", desc: "Generate QR codes for free online. Enter URL, text, or phone number to create custom QR codes. Customize QR code size and error correction level. Download as high-quality PNG. No signup required.", cat: "UtilitiesApplication" },
    password: { name: "Password Generator - Strong Random Password Generator - Secure Passwords", desc: "Generate strong, secure random passwords instantly. Create complex passwords with uppercase letters, lowercase letters, numbers, and symbols. Password strength meter. Cryptographically secure random generation.", cat: "SecurityApplication" },
    lotto: { name: "Lottery Number Generator - Powerball, Mega Millions, EuroMillions Numbers", desc: "Generate random lottery numbers for Powerball, Mega Millions, EuroMillions, UK Lotto, and custom lottery games. Cryptographically secure random number generation. Multiple draws at once.", cat: "EntertainmentApplication" },
    percent: { name: "Percentage Calculator - Free Online Percent Calculator - % of Number", desc: "Free online percentage calculator. Calculate what is X% of Y, X is what percent of Y, percentage change between two numbers, percentage increase and decrease. Fast and accurate. Mac OS 9 retro style.", cat: "UtilitiesApplication" },
    currency: { name: "Currency Converter - Free Online Exchange Rate Calculator - Forex Converter", desc: "Free online currency converter. Convert between 20 major world currencies including USD, EUR, GBP, JPY, KRW, CNY, BRL with live exchange rates. Bidirectional conversion. Updated daily.", cat: "UtilitiesApplication" },
    random: { name: "Random Number Generator - Free Online Randomizer - Pick Random Numbers", desc: "Generate cryptographically secure random numbers within any range. Choose count, enable unique mode to prevent duplicates, sort results. Perfect for giveaways, raffles, and statistical sampling.", cat: "UtilitiesApplication" },
    text: { name: "Text Tools - Word Counter, Character Counter, Case Converter, Base64 Encode Decode", desc: "Free online text tools: count characters and words, convert text between uppercase and lowercase and title case, encode and decode Base64. Count sentences, paragraphs, and lines.", cat: "UtilitiesApplication" },
    timer: { name: "Stopwatch & Timer - Free Online Stopwatch and Countdown Timer - Lap Timer", desc: "Free online stopwatch and countdown timer. Measure elapsed time with lap recording and split times. Set a countdown timer with alarm. Mac OS 9 retro style. Works on mobile and desktop.", cat: "UtilitiesApplication" },
    discount: { name: "Discount Calculator - Percent Off Calculator - Free Online Savings Calculator", desc: "Free online discount calculator: calculate final price after percentage discount, savings amount you save, and percent off. Reverse discount calculation. Mac OS 9 retro style.", cat: "UtilitiesApplication" },
    loan: { name: "Loan Calculator - Free Online Loan Payment Calculator - EMI Calculator", desc: "Free online loan calculator: calculate monthly payment (EMI), total interest, and total payment for any loan. Supports personal loans, auto loans, student loans. Amortization schedule included. Mac OS 9 retro style.", cat: "FinanceApplication" },
    compound: { name: "Compound Interest Calculator - Free Online Investment Calculator - Savings Growth", desc: "Free online compound interest calculator: see how your investments and savings grow over time with monthly contributions. Calculate future value, total interest earned, and total contributions. Year-by-year breakdown table. Mac OS 9 retro style.", cat: "FinanceApplication" },
    mortgage: { name: "Mortgage Calculator - Free Home Loan Payment Calculator - Mortgage Estimator", desc: "Free online mortgage calculator: estimate your monthly mortgage payment including principal, interest, property taxes, and home insurance. Full 30-year amortization schedule. Calculate how much house you can afford. Mac OS 9 retro style.", cat: "FinanceApplication" },
    bodyfat: { name: "Body Fat Calculator - Body Fat Percentage Calculator - US Navy Method", desc: "Free online body fat calculator: estimate your body fat percentage using the U.S. Navy circumference method. Input height, neck, waist (and hip for women). Color-coded category chart shows essential fat, athlete, fitness, acceptable, and obese ranges.", cat: "HealthApplication" },
    fraction: { name: "Fraction Calculator - Add, Subtract, Multiply, Divide Fractions - Free Online", desc: "Free online fraction calculator: add fractions, subtract fractions, multiply fractions, and divide fractions. Simplifies results to lowest terms. Converts between improper fractions and mixed numbers. Shows decimal equivalent. Perfect for math homework help.", cat: "MathApplication" },
    tip: { name: "Tip Calculator - Free Online Gratuity Calculator - Bill Split Calculator", desc: "Free online tip calculator and gratuity calculator: calculate tip amount, total bill including tip, and per person cost when splitting the bill. Choose 10%, 15%, 18%, or 20% tip or enter a custom percentage. Perfect for restaurant dinner bills, parties, and group dining.", cat: "FinanceApplication" },
    average: { name: "Average Calculator - Mean, Median, Mode Calculator - Free Online", desc: "Free online average calculator: calculate the mean, median, and mode of a set of numbers. Add multiple numbers and instantly see the average, sum, count, median, range, and mode. Perfect for students, teachers, and data analysis. Mac OS 9 retro style.", cat: "MathApplication" },
    age: { name: "Age Calculator - Exact Age in Years, Months, Days - Free Online Birthday Calculator", desc: "Free online age calculator: calculate your exact age in years, months, and days. Enter your date of birth to find out exactly how old you are, total days lived, day of the week you were born, and days until your next birthday. Accurate and easy to use.", cat: "UtilitiesApplication" },
    grade: { name: "Grade Calculator - GPA Calculator - Free Online Letter Grade Calculator", desc: "Free online grade calculator and GPA calculator: add subjects, scores, and weights to calculate your average score, GPA on a 4.0 scale, and letter grade (A/B/C/D/F). Perfect for students tracking academic performance. Mac OS 9 retro style.", cat: "EducationApplication" },
    duration: { name: "Time Duration Calculator - Calculate Time Between Dates - Free Online", desc: "Free online time duration calculator: calculate the exact time difference between two dates and times. See duration in years, months, weeks, days, hours, minutes, and seconds. Quick presets for today, last 7 days, last 30 days, last year. Mac OS 9 retro style.", cat: "UtilitiesApplication" },
    daysuntil: { name: "Days Until Calculator - Countdown Days Until Date - How Many Days Left", desc: "Free online days until calculator: find out how many days, weeks, months, and years until any target date. Countdown to Christmas, New Year, birthday, or any special event. Shows day of the week. Mac OS 9 retro style.", cat: "UtilitiesApplication" },
    wordcounter: { name: "Word Counter - Free Online Word Count, Character Count, Sentence Counter", desc: "Free online word counter tool: count words, characters (with and without spaces), sentences, paragraphs, lines, reading time, and speaking time. Paste any text for instant stats. Mac OS 9 retro style.", cat: "UtilitiesApplication" },
    idealweight: { name: "Ideal Weight Calculator - Healthy Body Weight Calculator - Devine Hamwi Formula", desc: "Free online ideal weight calculator: calculate your ideal body weight using Devine, Hamwi, Robinson, and Miller formulas. See healthy BMI weight range for your height. Metric and imperial units supported. Mac OS 9 retro style.", cat: "HealthApplication" },
    fuelcost: { name: "Fuel Cost Calculator - Trip Fuel Cost Estimator - Gas Calculator", desc: "Free online fuel cost calculator: estimate total fuel cost for any trip. Enter distance, fuel economy (L/100km or MPG), and fuel price. See total cost, fuel needed, cost per km/mile. Perfect for road trips. Mac OS 9 retro style.", cat: "UtilitiesApplication" },
    salary: { name: "Salary Calculator - Annual to Hourly Converter - Paycheck Calculator", desc: "Free online salary calculator: convert annual salary to hourly, daily, weekly, biweekly, and monthly pay. Enter hours and days per week. Perfect for job offer comparison and budgeting. Mac OS 9 retro style.", cat: "FinanceApplication" },
    overtime: { name: "Overtime Calculator - Overtime Pay Calculator - Time and a Half Calculator", desc: "Free online overtime calculator: calculate overtime pay with time-and-a-half (1.5x) and double-time (2x) rates. Enter hourly rate, regular hours, and overtime hours to see total pay including overtime. Perfect for hourly workers and payroll. Mac OS 9 retro style.", cat: "FinanceApplication" },
    retirement: { name: "Retirement Calculator - Retirement Savings Calculator - 401k IRA Planner", desc: "Free online retirement calculator: estimate your retirement savings with compound interest projections. Enter current age, retirement age, current savings, monthly contributions, and expected annual return. Shows 4% safe withdrawal rule and year-by-year growth table. Mac OS 9 retro style.", cat: "FinanceApplication" },
    duedate: { name: "Due Date Calculator - Pregnancy Due Date Calculator - Conception Date Estimator", desc: "Free online due date calculator: calculate your estimated due date, conception date, fertile window, and current pregnancy week using Naegele's rule. Enter first day of last menstrual period. Shows trimester schedule. Mac OS 9 retro style.", cat: "HealthApplication" },
    pace: { name: "Pace Calculator - Running Pace Calculator - Speed Distance Time Calculator", desc: "Free online pace calculator for runners: calculate running pace (min/km), speed (km/h), time, or distance. Enter any two values to find the third. Perfect for marathon training, 5K, 10K, and half marathon planning. Mac OS 9 retro style.", cat: "HealthApplication" },
    sip: { name: "SIP Calculator - Systematic Investment Plan Calculator - Mutual Fund Returns", desc: "Free online SIP calculator: estimate the maturity amount of your systematic investment plan. Enter monthly investment, time period, and expected return rate. Shows total invested vs estimated returns with year-by-year growth table. Mac OS 9 retro style.", cat: "FinanceApplication" },
    vat: { name: "VAT Calculator - Value Added Tax Calculator - GST Calculator", desc: "Free online VAT calculator: add or remove VAT/GST from any amount. Choose from 10 common VAT rates worldwide including UK, EU, India, Australia, Japan. Shows net amount, VAT amount, and gross amount. Mac OS 9 retro style.", cat: "FinanceApplication" },
    simpleinterest: { name: "Simple Interest Calculator - Easy Interest Calculator - Loan Interest", desc: "Free online simple interest calculator: calculate interest earned on any principal amount. Enter principal, interest rate, and time period in years, months, or days. Shows total interest and final amount. Mac OS 9 retro style.", cat: "FinanceApplication" },
    period: { name: "Period Calculator - Menstrual Cycle Calculator - Ovulation Calendar", desc: "Free online period calculator: track your menstrual cycle and predict next period, ovulation day, and fertile window. Enter last period date, cycle length, and period length. Shows days until next period. Mac OS 9 retro style.", cat: "HealthApplication" },
    markup: { name: "Markup Calculator - Margin and Markup Calculator - Profit Calculator", desc: "Free online markup calculator: calculate selling price, profit, and margin from cost and markup percentage. Perfect for retail pricing, e-commerce, and small business. Mac OS 9 retro style.", cat: "FinanceApplication" },
    waterintake: { name: "Water Intake Calculator - Daily Water Intake - How Much Water to Drink", desc: "Free online water intake calculator: calculate how much water you should drink daily based on your weight and exercise level. Shows results in ml, cups, and fl oz. Uses medical guidelines (33ml per kg). Mac OS 9 retro style.", cat: "HealthApplication" },
    salestax: { name: "Sales Tax Calculator - US State Sales Tax Calculator - Free Online", desc: "Free online US sales tax calculator: calculate sales tax for any US state. Add tax to a price or remove tax from a total. Includes 2026 state sales tax rates and average combined rates for all 50 states. Mac OS 9 retro style.", cat: "FinanceApplication" },
    petage: { name: "Pet Age Calculator - Dog Years to Human Years & Cat Age Calculator - Free Online", desc: "Free online pet age calculator: convert dog years and cat years to human years. Enter your pet's age, breed size (small, medium, large, giant), and species to get an accurate human-equivalent age. Uses AVMA veterinary formulas. Mac OS 9 retro style.", cat: "UtilitiesApplication" },
    love: { name: "Love Calculator - Love Percentage & Zodiac Compatibility - Free Online", desc: "Free online love calculator: calculate love compatibility between two names and zodiac signs. Get your love percentage, FLAMES result, and zodiac match score. Fun to share with friends and crushes. Mac OS 9 retro style.", cat: "EntertainmentApplication" },
    emi: { name: "EMI Calculator - Loan EMI Calculator - Monthly Payment Calculator - Free Online", desc: "Free online EMI calculator: calculate your monthly loan EMI (Equated Monthly Installment) for home loans, car loans, personal loans, and education loans. Enter loan amount, interest rate, and tenure to see EMI, total interest, and total payment with amortization schedule. Mac OS 9 retro style.", cat: "FinanceApplication" },
    sqft: { name: "Square Footage Calculator - Sq Ft Calculator - Room Area Calculator - Free Online", desc: "Free online square footage calculator: calculate the area of any room, house, or property in square feet. Supports rectangle, square, circle, and L-shaped rooms. Perfect for flooring, painting, tiling, and real estate. Mac OS 9 retro style.", cat: "UtilitiesApplication" },
    sleep: { name: "Sleep Calculator - Best Bedtime Calculator - Wake Up Refreshed - Free Online", desc: "Free online sleep calculator: find the best bedtime and wake-up time using sleep cycle science. Based on 90-minute sleep cycles, it calculates optimal times to wake up between cycles. Enter when you need to wake up or go to bed. Mac OS 9 retro style.", cat: "HealthApplication" },
  },
  es: {
    calorie: { name: "Calculadora de Calor\u00edas - BMR, TDEE y Macros", desc: "Calculadora de calor\u00edas gratuita: calcula BMR, TDEE, IMC y macronutrientes.", cat: "HealthApplication, Nutrition" },
    bmi: { name: "Calculadora de IMC - \u00cdndice de Masa Corporal", desc: "Calculadora de IMC gratuita: calcule su \u00cdndice de Masa Corporal.", cat: "HealthApplication" },
    convert: { name: "Conversor de Unidades - Longitud, Peso, Temperatura", desc: "Conversor de unidades gratuito: longitud, peso, temperatura, volumen, \u00e1rea, velocidad, presi\u00f3n.", cat: "UtilitiesApplication" },
    date: { name: "Calculadora de Fechas - D\u00edas Entre Fechas", desc: "Calculadora de fechas gratuita: calcule d\u00edas entre fechas, D-Day, edad.", cat: "UtilitiesApplication" },
    photo: { name: "Editor de Fotos - Redimensionar, Recortar, Comprimir", desc: "Editor de fotos gratuito: redimensione, recorte y comprima im\u00e1genes.", cat: "MultimediaApplication" },
    qr: { name: "Generador de C\u00f3digos QR - Creador Gratuito", desc: "Genera c\u00f3digos QR gratis. Ingresa URL o texto.", cat: "UtilitiesApplication" },
    password: { name: "Generador de Contrase\u00f1as - Contrase\u00f1a Segura", desc: "Genere contrase\u00f1as seguras y aleatorias.", cat: "SecurityApplication" },
    lotto: { name: "Generador de N\u00fameros de Loter\u00eda", desc: "Genere n\u00fameros de loter\u00eda aleatorios.", cat: "EntertainmentApplication" },
    percent: { name: "Calculadora de Porcentajes - Gratis Online", desc: "Calculadora de porcentajes gratuita. Calcula qu\u00e9 es X% de Y, qu\u00e9 porcentaje es X de Y.", cat: "UtilitiesApplication" },
    currency: { name: "Conversor de Moneda - Calculadora de Tipo de Cambio", desc: "Conversor de moneda gratuito entre 20 monedas principales.", cat: "UtilitiesApplication" },
    random: { name: "Generador de N\u00fameros Aleatorios - Gratis", desc: "Generador de n\u00fameros aleatorios criptogr\u00e1ficamente seguros.", cat: "UtilitiesApplication" },
    text: { name: "Herramientas de Texto - Contador, Convertir, Base64", desc: "Herramientas de texto gratuitas: contar caracteres, convertir may\u00fasculas/min\u00fasculas, Base64.", cat: "UtilitiesApplication" },
    timer: { name: "Cron\u00f3metro y Temporizador - Cron\u00f3metro Online Gratuito", desc: "Cron\u00f3metro online gratuito y temporizador de cuenta atr\u00e1s con registro de vueltas.", cat: "UtilitiesApplication" },
    discount: { name: "Calculadora de Descuento - Calculadora de Porcentaje de Descuento Gratuita", desc: "Calculadora de descuento gratuita: calcule el precio final despu\u00e9s del descuento y la cantidad ahorrada. Mac OS 9 retro style.", cat: "UtilitiesApplication" },
    loan: { name: "Calculadora de Pr\u00e9stamos - Calculadora de Pago de Pr\u00e9stamo Gratuita", desc: "Calculadora de pr\u00e9stamos gratuita: calcule pagos mensuales, inter\u00e9s total y amortizaci\u00f3n para cualquier pr\u00e9stamo. Interfaz retro Mac OS 9.", cat: "FinanceApplication" },
    compound: { name: "Calculadora de Inter\u00e9s Compuesto - Calculadora de Inversi\u00f3n Gratuita", desc: "Calculadora de inter\u00e9s compuesto gratuita: vea c\u00f3mo crecen sus inversiones con aportes mensuales. Desglose anual, estilo retro Mac OS 9.", cat: "FinanceApplication" },
    mortgage: { name: "Calculadora de Hipoteca - Calculadora de Pago de Vivienda Gratuita", desc: "Calculadora de hipoteca gratuita: calcule pagos mensuales incluyendo capital, inter\u00e9s, impuestos y seguro. Tabla de amortizaci\u00f3n, estilo retro Mac OS 9.", cat: "FinanceApplication" },
    bodyfat: { name: "Calculadora de Grasa Corporal - Calculadora de Porcentaje de Grasa", desc: "Calculadora de grasa corporal gratuita: estime su porcentaje de grasa corporal usando el m\u00e9todo de la Armada de EE.UU. Gr\u00e1fico de categor\u00edas, estilo retro Mac OS 9.", cat: "HealthApplication" },
  fraction: { name: "Calculadora de Fracciones - Sumar, Restar, Multiplicar, Dividir Fracciones - Simplificar Fracciones", desc: "Calculadora de fracciones gratuita: sumar fracciones, restar fracciones, multiplicar fracciones y dividir fracciones. Simplifica resultados a la fracción irreducible. Convierte entre fracciones impropias y números mixtos. Muestra el equivalente decimal. Ideal para tareas de matemáticas.", cat: "MathApplication" },
    tip: { name: "Calculadora de Propinas - Calculadora de Gratificación Gratuita - Dividir Cuenta", desc: "Calculadora de propinas gratuita: calcule el monto de la propina, el total de la cuenta y el costo por persona. Elija 10%, 15%, 18% o 20% de propina o ingrese un porcentaje personalizado.", cat: "FinanceApplication" },
    average: { name: "Calculadora de Promedio - Calcular Media, Mediana, Moda - Gratis", desc: "Calculadora de promedio gratuita: calcule la media, mediana y moda de un conjunto de números. Agregue múltiples números y vea el promedio, suma, mediana, rango y moda al instante. Estilo retro Mac OS 9.", cat: "MathApplication" },
    age: { name: "Calculadora de Edad - Edad Exacta en Años, Meses, Días - Calculadora de Cumpleaños", desc: "Calculadora de edad gratuita: calcule su edad exacta en años, meses y días. Ingrese su fecha de nacimiento para saber su edad, días vividos, día de la semana que nació y días hasta su próximo cumpleaños.", cat: "UtilitiesApplication" },
    grade: { name: "Calculadora de Calificaciones - Calculadora GPA - Calculadora de Notas", desc: "Calculadora de calificaciones gratuita: agregue materias, puntajes y pesos para calcular su puntaje promedio, GPA en escala 4.0 y calificación por letras. Estilo retro Mac OS 9.", cat: "EducationApplication" },
    duration: { name: "Calculadora de Duración de Tiempo - Calcular Tiempo Entre Fechas", desc: "Calculadora de duración de tiempo gratuita: calcule la diferencia exacta entre dos fechas y horas. Vea la duración en años, meses, semanas, días, horas, minutos y segundos. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    daysuntil: { name: "Calculadora de Días Hasta - Cuenta Regresiva de Días", desc: "Calculadora de días hasta gratuita: descubra cuántos días, semanas, meses y años faltan para cualquier fecha objetivo. Cuenta regresiva para Navidad, Año Nuevo. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    wordcounter: { name: "Contador de Palabras - Contador de Palabras y Caracteres Gratis", desc: "Contador de palabras gratuito: cuente palabras, caracteres (con y sin espacios), oraciones, párrafos, líneas, tiempo de lectura y habla. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    idealweight: { name: "Calculadora de Peso Ideal - Peso Saludable - Fórmulas Devine Hamwi", desc: "Calculadora de peso ideal gratuita: calcule su peso ideal usando las fórmulas Devine, Hamwi, Robinson y Miller. Vea el rango de peso saludable del IMC. Estilo retro Mac OS 9.", cat: "HealthApplication" },
    fuelcost: { name: "Calculadora de Costo de Combustible - Estimador de Gastos de Gasolina", desc: "Calculadora de costo de combustible gratuita: estime el costo total de combustible para cualquier viaje. Ingrese distancia, consumo y precio. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    salary: { name: "Calculadora de Salario - Convertir Anual a Por Hora", desc: "Calculadora de salario gratuita: convierta salario anual en pago por hora, día, semana, quincena y mes. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    overtime: { name: "Calculadora de Horas Extras - Pago de Horas Extra", desc: "Calculadora de horas extras gratuita: calcule el pago de horas extras con tarifa 1.5x y 2x. Ingrese tarifa por hora, horas regulares y horas extras. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    retirement: { name: "Calculadora de Jubilación - Planificador de Retiro", desc: "Calculadora de jubilación gratuita: estime sus ahorros para el retiro con proyecciones de interés compuesto. Muestra la regla de retiro seguro del 4%. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    duedate: { name: "Calculadora de Fecha de Parto - Embarazo", desc: "Calculadora de fecha de parto gratuita: calcule su fecha probable de parto, fecha de concepción y semana actual de embarazo usando la regla de Naegele. Estilo retro Mac OS 9.", cat: "HealthApplication" },
    pace: { name: "Calculadora de Ritmo - Ritmo de Carrera", desc: "Calculadora de ritmo gratuita para corredores: calcule ritmo (min/km), velocidad (km/h), tiempo o distancia. Perfecta para entrenamiento de maratón. Estilo retro Mac OS 9.", cat: "HealthApplication" },
    sip: { name: "Calculadora SIP - Plan de Inversión Sistemática", desc: "Calculadora SIP gratuita: estime el monto de vencimiento de su plan de inversión sistemática. Ingrese inversión mensual, plazo y rendimiento esperado. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    vat: { name: "Calculadora de IVA - Impuesto al Valor Agregado", desc: "Calculadora de IVA gratuita: agregue o quite IVA de cualquier cantidad. Elija entre 10 tasas comunes. Muestra monto neto, IVA y monto bruto. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    simpleinterest: { name: "Calculadora de Interés Simple", desc: "Calculadora de interés simple gratuita: calcule intereses sobre cualquier capital. Ingrese capital, tasa y plazo. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    period: { name: "Calculadora de Período Menstrual", desc: "Calculadora de período menstrual gratuita: prediga su próximo período y ventana fértil. Estilo retro Mac OS 9.", cat: "HealthApplication" },
    markup: { name: "Calculadora de Margen - Margen de Ganancia", desc: "Calculadora de margen gratuita: calcule precio de venta, ganancia y margen. Perfecta para comercio minorista. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    waterintake: { name: "Calculadora de Agua Diaria", desc: "Calculadora de agua gratuita: calcule cuánta agua debe beber según su peso y ejercicio. Estilo retro Mac OS 9.", cat: "HealthApplication" },
    salestax: { name: "Calculadora de Impuesto a las Ventas - Impuesto Estatal EE.UU.", desc: "Calculadora de impuesto a las ventas gratuita: calcule el impuesto a las ventas para cualquier estado de EE.UU. Agregue o quite impuesto de un precio. Incluye tasas de 2026 para los 50 estados. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    petage: { name: "Calculadora de Edad de Mascotas - Edad de Perros y Gatos en Años Humanos", desc: "Calculadora gratuita de edad de mascotas: convierta años de perros y gatos a años humanos. Ingrese la edad, tamaño y especie de su mascota. Utiliza fórmulas veterinarias AVMA. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    love: { name: "Calculadora de Amor - Compatibilidad de Nombres y Zodiaco - Gratis", desc: "Calculadora de amor gratuita: calcule la compatibilidad amorosa entre dos nombres y signos zodiacales. Obtenga su porcentaje de amor, resultado FLAMES y puntuación zodiacal. Estilo retro Mac OS 9.", cat: "EntertainmentApplication" },
    emi: { name: "Calculadora de EMI - Cuota Mensual de Préstamo - Calculadora de Pago Mensual", desc: "Calculadora de EMI gratuita: calcule su cuota mensual (EMI) para préstamos hipotecarios, de auto, personales y educativos. Ingrese monto, tasa de interés y plazo. Muestra tabla de amortización. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    sqft: { name: "Calculadora de Metraje Cuadrado - Calculadora de Área de Habitación", desc: "Calculadora de metraje cuadrado gratuita: calcule el área de cualquier habitación, casa o propiedad en pies cuadrados. Soporta rectángulo, cuadrado, círculo y forma de L. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    sleep: { name: "Calculadora de Sueño - Mejor Hora de Acostarse - Despertar Descansado", desc: "Calculadora de sueño gratuita: encuentre la mejor hora para acostarse y despertarse usando la ciencia del ciclo del sueño. Basada en ciclos de 90 minutos. Estilo retro Mac OS 9.", cat: "HealthApplication" },
  },
  zh: {
    calorie: { name: "\u5361\u8def\u91cc\u8ba1\u7b97\u5668 - BMR\u3001TDEE\u548c\u5b8f\u517b\u6210\u5206", desc: "\u514d\u8d39\u5728\u7ebf\u5361\u8def\u91cc\u8ba1\u7b97\u5668\uff1a\u8ba1\u7b97BMR\u3001TDEE\u3001BMI\u548c\u5b8f\u517b\u6210\u5206\u3002", cat: "HealthApplication, Nutrition" },
    bmi: { name: "BMI\u8ba1\u7b97\u5668 - \u8eab\u4f53\u8d28\u91cf\u6307\u6570", desc: "\u8ba1\u7b97\u60a8\u7684\u8eab\u4f53\u8d28\u91cf\u6307\u6570\uff08BMI\uff09\u3002", cat: "HealthApplication" },
    convert: { name: "\u5355\u4f4d\u6362\u7b97\u5668 - \u957f\u5ea6\u3001\u91cd\u91cf\u3001\u6e29\u5ea6", desc: "\u514d\u8d39\u5355\u4f4d\u6362\u7b97\u5668\uff1a\u957f\u5ea6\u3001\u91cd\u91cf\u3001\u6e29\u5ea6\u3001\u4f53\u79ef\u3002", cat: "UtilitiesApplication" },
    date: { name: "\u65e5\u671f\u8ba1\u7b97\u5668 - \u65e5\u671f\u95f4\u9699", desc: "\u514d\u8d39\u65e5\u671f\u8ba1\u7b97\u5668\uff1a\u8ba1\u7b97\u65e5\u671f\u95f4\u9699\u3001D-Day\u3002", cat: "UtilitiesApplication" },
    photo: { name: "\u7167\u7247\u7f16\u8f91\u5668 - \u8c03\u6574\u5927\u5c0f\u3001\u88c1\u526a", desc: "\u514d\u8d39\u5728\u7ebf\u7167\u7247\u7f16\u8f91\u5668\u3002", cat: "MultimediaApplication" },
    qr: { name: "QR\u7801\u751f\u6210\u5668 - \u514d\u8d39\u5728\u7ebf", desc: "\u514d\u8d39\u751f\u6210QR\u7801\u3002", cat: "UtilitiesApplication" },
    password: { name: "\u5bc6\u7801\u751f\u6210\u5668 - \u5f3a\u968f\u673a\u5bc6\u7801", desc: "\u751f\u6210\u5f3a\u5927\u5b89\u5168\u7684\u968f\u673a\u5bc6\u7801\u3002", cat: "SecurityApplication" },
    lotto: { name: "\u5f69\u7968\u53f7\u7801\u751f\u6210\u5668", desc: "\u751f\u6210\u968f\u673a\u5f69\u7968\u53f7\u7801\u3002", cat: "EntertainmentApplication" },
    percent: { name: "\u767e\u5206\u6bd4\u8ba1\u7b97\u5668 - \u514d\u8d39\u5728\u7ebf", desc: "\u514d\u8d39\u767e\u5206\u6bd4\u8ba1\u7b97\u5668\u3002\u8ba1\u7b97 X \u7684 Y%\u3001X \u662f Y \u7684\u767e\u5206\u4e4b\u51e0\u3002", cat: "UtilitiesApplication" },
    currency: { name: "\u8d27\u5e01\u8f6c\u6362\u5668 - \u514d\u8d39\u6c47\u7387\u8ba1\u7b97", desc: "\u572820\u79cd\u4e3b\u8981\u8d27\u5e01\u4e4b\u95f4\u8fdb\u884c\u8f6c\u6362\u3002", cat: "UtilitiesApplication" },
    random: { name: "\u968f\u673a\u6570\u751f\u6210\u5668 - \u514d\u8d39\u5728\u7ebf", desc: "\u5728\u4efb\u610f\u8303\u56f4\u5185\u751f\u6210\u5bc6\u7801\u5b66\u5b89\u5168\u7684\u968f\u673a\u6570\u3002", cat: "UtilitiesApplication" },
    text: { name: "\u6587\u672c\u5de5\u5177 - \u5b57\u7b26\u8ba1\u6570\u3001\u5927\u5c0f\u5199\u8f6c\u6362\u3001Base64", desc: "\u514d\u8d39\u6587\u672c\u5de5\u5177\uff1a\u7edf\u8ba1\u5b57\u7b26\u548c\u5355\u8bcd\u3001\u8f6c\u6362\u5927\u5c0f\u5199\u3001Base64\u7f16\u7801/\u89e3\u7801\u3002", cat: "UtilitiesApplication" },
    timer: { name: "\u79d2\u8868\u548c\u8ba1\u65f6\u5668 - \u514d\u8d39\u5728\u7ebf\u79d2\u8868\u548c\u5012\u8ba1\u65f6", desc: "\u514d\u8d39\u5728\u7ebf\u79d2\u8868\u548c\u5012\u8ba1\u65f6\u5668\u3002\u8bb0\u5f55\u7ecf\u8fc7\u65f6\u95f4\u548c\u8ba1\u6b21\uff0c\u6216\u8bbe\u7f6e\u5012\u8ba1\u65f6\u3002", cat: "UtilitiesApplication" },
    discount: { name: "\u6298\u6263\u8ba1\u7b97\u5668 - \u514d\u8d39\u5728\u7ebf\u6298\u6263\u8ba1\u7b97\u5668", desc: "\u514d\u8d39\u5728\u7ebf\u6298\u6263\u8ba1\u7b97\u5668\uff1a\u8ba1\u7b97\u6298\u6263\u540e\u7684\u6700\u7ec8\u4ef7\u683c\u548c\u60a8\u8282\u7701\u7684\u91d1\u989d\u3002Mac OS 9\u590d\u53e4\u98ce\u683c\u3002", cat: "UtilitiesApplication" },
    loan: { name: "\u8d37\u6b3e\u8ba1\u7b97\u5668 - \u514d\u8d39\u5728\u7ebf\u8d37\u6b3e\u8ba1\u7b97\u5668", desc: "\u514d\u8d39\u5728\u7ebf\u8d37\u6b3e\u8ba1\u7b97\u5668\uff1a\u8ba1\u7b97\u6bcf\u6708\u8fd8\u6b3e\u3001\u603b\u5229\u606f\u548c\u5206\u671f\u4ed8\u6b3e\u8868\u3002Mac OS 9\u590d\u53e4\u98ce\u683c\u3002", cat: "FinanceApplication" },
    compound: { name: "\u590d\u5229\u8ba1\u7b97\u5668 - \u514d\u8d39\u5728\u7ebf\u6295\u8d44\u8ba1\u7b97\u5668", desc: "\u514d\u8d39\u590d\u5229\u8ba1\u7b97\u5668\uff1a\u67e5\u770b\u60a8\u7684\u6295\u8d44\u968f\u7740\u6708\u5b58\u800c\u589e\u957f\u7684\u60c5\u51b5\u3002\u5e74\u5ea6\u8be6\u7ec6\u62c6\u89e3\uff0cMac OS 9\u590d\u53e4\u98ce\u683c\u3002", cat: "FinanceApplication" },
    mortgage: { name: "\u623f\u8d37\u8ba1\u7b97\u5668 - \u514d\u8d39\u5728\u7ebf\u623f\u5c4b\u8d37\u6b3e\u8ba1\u7b97\u5668", desc: "\u514d\u8d39\u623f\u8d37\u8ba1\u7b97\u5668\uff1a\u4f30\u7b97\u6bcf\u6708\u8fd8\u6b3e\u5305\u62ec\u672c\u91d1\u3001\u5229\u606f\u3001\u7a0e\u8d39\u548c\u4fdd\u9669\u3002\u5206\u671f\u4ed8\u6b3e\u8868\uff0cMac OS 9\u590d\u53e4\u98ce\u683c\u3002", cat: "FinanceApplication" },
    bodyfat: { name: "\u4f53\u8102\u7387\u8ba1\u7b97\u5668 - \u4f53\u8102\u767e\u5206\u6bd4\u8ba1\u7b97\u5668", desc: "\u514d\u8d39\u4f53\u8102\u7387\u8ba1\u7b97\u5668\uff1a\u4f7f\u7528\u7f8e\u56fd\u6d77\u519b\u65b9\u6cd5\u4f30\u7b97\u60a8\u7684\u4f53\u8102\u7387\u3002\u989c\u8272\u7f16\u7801\u56fe\u8868\uff0cMac OS 9\u590d\u53e4\u98ce\u683c\u3002", cat: "HealthApplication" },
  fraction: { name: "分数计算器 - 分数加减乘除 - 在线分数化简器 - 带分数计算器", desc: "免费在线分数计算器：分数加法、分数减法、分数乘法、分数除法。自动将结果化简为最简分数。支持假分数和带分数互转。显示小数等效值。适合数学作业辅助。", cat: "MathApplication" },
    tip: { name: "小费计算器 - 免费在线小费计算器 - 账单分摊", desc: "免费在线小费计算器：输入账单金额和小费比例，计算小费金额、总账单和每人分摊费用。支持10%、15%、18%、20%预设比例或自定义。", cat: "FinanceApplication" },
    average: { name: "平均值计算器 - 计算平均值、中位数、众数 - 免费在线", desc: "免费在线平均值计算器：计算一组数字的平均值、中位数和众数。添加多个数字，立即查看平均值、总和、个数、中位数、范围和众数。Mac OS 9 复古风格。", cat: "MathApplication" },
    age: { name: "年龄计算器 - 精确年龄(年/月/日) - 免费在线生日计算器", desc: "免费在线年龄计算器：计算您的精确年龄(年/月/日)。输入出生日期，查看您的年龄、已生存总天数、出生星期和距离下次生日的倒计时。", cat: "UtilitiesApplication" },
    grade: { name: "成绩计算器 - GPA计算器 - 免费在线成绩等级计算器", desc: "免费成绩计算器：添加科目、成绩和权重，计算您的平均成绩、GPA(4.0标准)和等级(A/B/C/D/F)。Mac OS 9 复古风格。", cat: "EducationApplication" },
    duration: { name: "时间时长计算器 - 计算两个日期之间的时间差", desc: "免费在线时间时长计算器：计算两个日期和时间之间的精确差异。以年、月、周、天、小时、分钟、秒显示时长。支持快速预设：今天、最近7天、最近30天、最近1年。Mac OS 9 复古风格。", cat: "UtilitiesApplication" },
    daysuntil: { name: "距离日期计算器 - 距离目标日期还有多少天", desc: "免费在线距离日期计算器：计算距离圣诞节、新年、生日或任何目标日期还有多少天、周、月和年。显示星期。Mac OS 9 复古风格。", cat: "UtilitiesApplication" },
    wordcounter: { name: "字数统计工具 - 在线字数、字符、句子计数器", desc: "免费在线字数统计工具：统计字数、字符数（含/不含空格）、句子数、段落数、行数、阅读时间和说话时间。Mac OS 9 复古风格。", cat: "UtilitiesApplication" },
    idealweight: { name: "理想体重计算器 - 健康体重计算 - Devine Hamwi 公式", desc: "免费在线理想体重计算器：使用 Devine、Hamwi、Robinson 和 Miller 公式计算您的理想体重。查看健康 BMI 体重范围。Mac OS 9 复古风格。", cat: "HealthApplication" },
    fuelcost: { name: "燃油费用计算器 - 行程油费估算", desc: "免费在线燃油费用计算器：估算任何行程的燃油总费用。输入距离、油耗和油价。Mac OS 9 复古风格。", cat: "UtilitiesApplication" },
    salary: { name: "薪资计算器 - 年薪转时薪 - 工资计算器", desc: "免费在线薪资计算器：将年薪转换为时薪、日薪、周薪、双周薪和月薪。Mac OS 9 复古风格。", cat: "FinanceApplication" },
    overtime: { name: "加班费计算器 - 加班工资计算", desc: "免费在线加班费计算器：计算加班工资。输入时薪、正常工时和加班工时。支持1.5倍和2倍加班费率。Mac OS 9 复古风格。", cat: "FinanceApplication" },
    retirement: { name: "退休金计算器 - 退休储蓄规划", desc: "免费在线退休金计算器：通过复利预估退休储蓄。输入当前年龄、退休年龄、现有储蓄和月供款。显示4%安全提款规则。Mac OS 9 复古风格。", cat: "FinanceApplication" },
    duedate: { name: "预产期计算器 - 怀孕预产期估算", desc: "免费在线预产期计算器：使用Naegele规则计算预产期、受孕日期和当前孕周。显示孕期阶段。Mac OS 9 复古风格。", cat: "HealthApplication" },
    pace: { name: "配速计算器 - 跑步配速计算", desc: "免费在线跑步配速计算器：计算配速、速度、时间或距离。输入任意两个值推算出第三个。适合马拉松训练。Mac OS 9 复古风格。", cat: "HealthApplication" },
    sip: { name: "SIP计算器 - 系统投资计划", desc: "免费在线SIP计算器：估算系统投资计划的到期金额。输入每月投资、期限和预期回报率。Mac OS 9 复古风格。", cat: "FinanceApplication" },
    vat: { name: "增值税计算器 - GST计算器", desc: "免费在线增值税计算器：添加或扣除增值税。选择10种常见税率。显示不含税金额、增值税和含税金额。Mac OS 9 复古风格。", cat: "FinanceApplication" },
    simpleinterest: { name: "单利计算器", desc: "免费在线单利计算器：计算本金的利息。输入本金、利率和期限。显示总利息和最终金额。Mac OS 9 复古风格。", cat: "FinanceApplication" },
    period: { name: "生理周期计算器", desc: "免费在线生理周期计算器：预测下次月经、排卵日和排卵期。Mac OS 9 复古风格。", cat: "HealthApplication" },
    markup: { name: "加价率计算器 - 利润率计算", desc: "免费在线加价率计算器：从成本和加价率计算售价、利润和毛利率。Mac OS 9 复古风格。", cat: "FinanceApplication" },
    waterintake: { name: "每日饮水量计算器", desc: "免费在线每日饮水量计算器：根据体重和运动量计算每日饮水量。Mac OS 9 复古风格。", cat: "HealthApplication" },
    salestax: { name: "销售税计算器 - 美国各州销售税计算器", desc: "免费在线美国销售税计算器：为任何美国州计算销售税。对价格加税或从总额中退税。包含2026年各州销售税率。Mac OS 9 复古风格。", cat: "FinanceApplication" },
    petage: { name: "宠物年龄计算器 - 狗年与猫年转人类年龄计算器", desc: "免费在线宠物年龄计算器：将狗年和猫年转换为人类年龄。输入宠物年龄、体型(小型/中型/大型/巨型)和物种，获得准确的人类等效年龄。基于AVMA兽医公式。Mac OS 9 复古风格。", cat: "UtilitiesApplication" },
    love: { name: "爱情计算器 - 姓名配对与星座配对 - 免费在线", desc: "免费在线爱情计算器：通过姓名和星座计算爱情匹配度。获取爱情百分比、FLAMES结果和星座配对分数。适合与朋友分享的趣味工具。Mac OS 9 复古风格。", cat: "EntertainmentApplication" },
    emi: { name: "EMI计算器 - 贷款月供计算器 - 房贷车贷计算", desc: "免费在线EMI计算器：计算贷款月供(等额本息)。支持房贷、车贷、个人贷款和教育贷款。输入金额、利率和期限，查看月供、总利息和还款计划表。Mac OS 9 复古风格。", cat: "FinanceApplication" },
    sqft: { name: "面积计算器 - 平方英尺计算器 - 房间面积计算", desc: "免费在线面积计算器：计算房间、房屋或房产面积(平方英尺)。支持长方形、正方形、圆形和L形房间。适合地板、油漆、瓷砖和房地产使用。Mac OS 9 复古风格。", cat: "UtilitiesApplication" },
    sleep: { name: "睡眠计算器 - 最佳就寝时间 - 醒来精神饱满", desc: "免费在线睡眠计算器：通过睡眠周期科学找到最佳入睡和起床时间。基于90分钟睡眠周期，计算周期之间最佳醒来时间。Mac OS 9 复古风格。", cat: "HealthApplication" },
  },
  ko: {
    calorie: { name: "\uce7c\ub85c\ub9ac \uacc4\uc0b0\uae30 - BMR, TDEE & \uc601\uc591\uc18c", desc: "\ubb34\ub8cc \uc628\ub77c\uc778 \uce7c\ub85c\ub9ac \uacc4\uc0b0\uae30: BMR, TDEE, BMI, \uc601\uc591\uc18c\ub97c \uacc4\uc0b0\ud569\ub2c8\ub2e4.", cat: "HealthApplication, Nutrition" },
    bmi: { name: "BMI \uacc4\uc0b0\uae30 - \uccb4\uc9c8\ub7c9\uc9c0\uc218", desc: "\ubb34\ub8cc BMI \uacc4\uc0b0\uae30: \uccb4\uc9c8\ub7c9\uc9c0\uc218\ub97c \uacc4\uc0b0\ud558\uace0 \uccb4\uc911 \uce74\ud14c\uace0\ub9ac\ub97c \ud655\uc778\ud558\uc138\uc694.", cat: "HealthApplication" },
    convert: { name: "\ub2e8\uc704 \ubcc0\ud658\uae30 - \uae38\uc774\u00b7\ubb34\uac8c\u00b7\uc628\ub3c4", desc: "\ubb34\ub8cc \ub2e8\uc704 \ubcc0\ud658\uae30: \uae38\uc774, \ubb34\uac8c, \uc628\ub3c4, \ubd80\ud53c, \uba74\uc801, \uc18d\ub3c4, \uc555\ub825.", cat: "UtilitiesApplication" },
    date: { name: "\ub0a0\uc9dc \uacc4\uc0b0\uae30 - \ub0a0\uc9dc \uac04\uaca9, D-Day", desc: "\ubb34\ub8cc \ub0a0\uc9dc \uacc4\uc0b0\uae30: \ub0a0\uc9dc \uac04\uaca9, D-Day, \ub098\uc774 \uacc4\uc0b0.", cat: "UtilitiesApplication" },
    photo: { name: "\uc0ac\uc9c4 \ud3b8\uc9d1\uae30 - \ub9ac\uc0ac\uc774\uc988\u00b7\uc790\ub974\uae30", desc: "\ubb34\ub8cc \uc628\ub77c\uc778 \uc0ac\uc9c4 \ud3b8\uc9d1\uae30.", cat: "MultimediaApplication" },
    qr: { name: "QR \ucf54\ub4dc \uc0dd\uc131\uae30 - \ubb34\ub8cc", desc: "\ubb34\ub8cc\ub85c QR \ucf54\ub4dc\ub97c \uc0dd\uc131\ud558\uc138\uc694.", cat: "UtilitiesApplication" },
    password: { name: "\ube44\ubc00\ubc88\ud638 \uc0dd\uc131\uae30 - \uac15\ub825\ud55c \ub79c\ub364", desc: "\uac15\ub825\ud558\uace0 \uc548\uc804\ud55c \ub79c\ub364 \ube44\ubc00\ubc88\ud638\ub97c \uc0dd\uc131\ud569\ub2c8\ub2e4.", cat: "SecurityApplication" },
    lotto: { name: "\ub85c\ub610 \ubc88\ud638 \uc0dd\uc131\uae30", desc: "\ub85c\ub610, \ud30c\uc6cc\ubcfc, \uba54\uac00\ubc00\ub9ac\uc5b8\uc988 \ubc88\ud638 \uc0dd\uc131.", cat: "EntertainmentApplication" },
    percent: { name: "\ud37c\uc13c\ud2b8 \uacc4\uc0b0\uae30 - \ubb34\ub8cc \uc628\ub77c\uc778", desc: "\ubb34\ub8cc \ud37c\uc13c\ud2b8 \uacc4\uc0b0\uae30. X\uc758 Y%, X\ub294 Y\uc758 \uba87% \uacc4\uc0b0, \ud37c\uc13c\ud2b8 \ubcc0\ud654.", cat: "UtilitiesApplication" },
    currency: { name: "\ud1b5\ud654 \ubcc0\ud658\uae30 - \ubb34\ub8cc \ud658\uc728 \uacc4\uc0b0\uae30", desc: "\ubb34\ub8cc \ud1b5\ud654 \ubcc0\ud658\uae30. 20\uac1c \uc8fc\uc694 \ud1b5\ud654 \uac04 \uc2e4\uc2dc\uac04 \ud658\uc728 \ubcc0\ud658.", cat: "UtilitiesApplication" },
    random: { name: "\ub79c\ub364 \uc22b\uc790 \uc0dd\uc131\uae30 - \ubb34\ub8cc", desc: "\uc784\uc758 \ubc94\uc704\uc5d0\uc11c \uc548\uc804\ud55c \ub79c\ub364 \uc22b\uc790\ub97c \uc0dd\uc131\ud569\ub2c8\ub2e4.", cat: "UtilitiesApplication" },
    text: { name: "\ud14d\uc2a4\ud2b8 \ub3c4\uad6c - \uae00\uc790\uc218, \ub300\uc18c\ubb38\uc790, Base64", desc: "\ubb34\ub8cc \ud14d\uc2a4\ud2b8 \ub3c4\uad6c: \uae00\uc790\uc218 \uacc4\uc0b0, \ub300\uc18c\ubb38\uc790 \ubcc0\ud658, Base64 \uc778\ucf54\ub529/\ub514\ucf54\ub529.", cat: "UtilitiesApplication" },
    timer: { name: "\uc2a4\ud1b1\uc6cc\uce58 & \ud0c0\uc774\uba38 - \ubb34\ub8cc \uc628\ub77c\uc778 \uc2a4\ud1b1\uc6cc\uce58", desc: "\ubb34\ub8cc \uc628\ub77c\uc778 \uc2a4\ud1b1\uc6cc\uce58 \ubc0f \uce74\uc6b4\ud2b8\ub2e4\uc6b4 \ud0c0\uc774\uba38. \ub7a9 \uae30\ub85d\uacfc \ud568\uaed8 \uacbd\uacfc \uc2dc\uac04 \uce21\uc815.", cat: "UtilitiesApplication" },
    discount: { name: "\ud560\uc778 \uacc4\uc0b0\uae30 - \ubb34\ub8cc \uc628\ub77c\uc778 \ud560\uc778\uc728 \uacc4\uc0b0\uae30", desc: "\ubb34\ub8cc \uc628\ub77c\uc778 \ud560\uc778 \uacc4\uc0b0\uae30: \ud560\uc778 \ud6c4 \ucd5c\uc885 \uac00\uaca9\uacfc \uc808\uc57d \uae08\uc561\uc744 \uacc4\uc0b0\ud569\ub2c8\ub2e4. Mac OS 9 \ubcf5\uace0 \uc2a4\ud0c0\uc77c.", cat: "UtilitiesApplication" },
    loan: { name: "\ub300\ucd9c \uacc4\uc0b0\uae30 - \ubb34\ub8cc \uc628\ub77c\uc778 \ub300\ucd9c \uacc4\uc0b0\uae30", desc: "\ubb34\ub8cc \uc628\ub77c\uc778 \ub300\ucd9c \uacc4\uc0b0\uae30: \uc6d4 \uc0c1\ud658\uc561, \ucd1d \uc774\uc790\ub97c \uacc4\uc0b0\ud569\ub2c8\ub2e4. Mac OS 9 \ubcf5\uace0 \uc2a4\ud0c0\uc77c.", cat: "FinanceApplication" },
    compound: { name: "\ubcf5\ub9ac \uacc4\uc0b0\uae30 - \ubb34\ub8cc \uc628\ub77c\uc778 \ud22c\uc790 \uacc4\uc0b0\uae30", desc: "\ubb34\ub8cc \ubcf5\ub9ac \uacc4\uc0b0\uae30: \uc6d4 \uc801\uae08\uc73c\ub85c \ubaa9\ub3c8\uc774 \uc5bc\ub9c8\ub098 \ubd88\ub9ac\ub294\uc9c0 \ud655\uc778\ud558\uc138\uc694. \ub144\ub3c4\ubcc4 \uc0c1\uc138 \ub0b4\uc5ed. Mac OS 9 \ubcf5\uace0 \uc2a4\ud0c0\uc77c.", cat: "FinanceApplication" },
    mortgage: { name: "\uc8fc\ud0dd\ub2f4\ubcf4 \ub300\ucd9c \uacc4\uc0b0\uae30 - \ubb34\ub8cc \uc628\ub77c\uc778 \uc8fc\ud0dd\ub2f4\ubcf4 \uacc4\uc0b0\uae30", desc: "\ubb34\ub8cc \uc8fc\ud0dd\ub2f4\ubcf4 \ub300\ucd9c \uacc4\uc0b0\uae30: \uc6d4 \uc0c1\ud658\uc561, \uc774\uc790, \uc7ac\uc0b0\uc138, \ubcf4\ud5d8\ub8cc\ub97c \ud3ec\ud568\ud55c \uacc4\uc0b0. \uc0c1\ud658 \uc77c\uc815\ud45c, Mac OS 9 \ubcf5\uace0 \uc2a4\ud0c0\uc77c.", cat: "FinanceApplication" },
    bodyfat: { name: "\uccb4\uc9c0\ubc29\uc728 \uacc4\uc0b0\uae30 - \uccb4\uc9c0\ubc29 \ubc31\ubd84\uc728 \uacc4\uc0b0\uae30", desc: "\ubb34\ub8cc \uccb4\uc9c0\ubc29\uc728 \uacc4\uc0b0\uae30: \ubbf8\uad6d \ud574\uad70 US Navy \ubc29\uc2dd\uc73c\ub85c \uccb4\uc9c0\ubc29\uc728\uc744 \ucd94\uc815\ud569\ub2c8\ub2e4. \uac83\ub0b4 \uc2e4\ud328 \uc0c9\uc0c1 \uce74\ud14c\uace0\ub9ac\ud45c, Mac OS 9 \ubcf5\uace0 \uc2a4\ud0c0\uc77c.", cat: "HealthApplication" },
  fraction: { name: "분수 계산기 - 분수 덧셈, 뺄셈, 곱셈, 나눗셈 - 분수 약분 계산기", desc: "무료 온라인 분수 계산기: 분수 더하기, 분수 빼기, 분수 곱하기, 분수 나누기. 결과를 자동으로 기약분수로 약분합니다. 가분수와 대분수 변환을 지원합니다. 소수 형태도 함께 표시합니다. 수학 숙제에 완벽한 도구입니다.", cat: "MathApplication" },
    tip: { name: "팁 계산기 - 무료 온라인 팁 계산기 - 더치페이 계산기", desc: "무료 온라인 팁 계산기: 팁 금액, 총 계산서, 인당 부담 금액을 계산합니다. 10%, 15%, 18%, 20% 프리셋 또는 직접 입력. 식당 계산서, 더치페이에 완벽한 도구입니다.", cat: "FinanceApplication" },
    average: { name: "평균 계산기 - 평균, 중앙값, 최빈값 계산기 - 무료 온라인", desc: "무료 온라인 평균 계산기: 여러 숫자의 평균, 중앙값, 최빈값을 계산합니다. 숫자를 추가하면 평균, 합계, 개수, 중앙값, 범위, 최빈값을 바로 확인할 수 있습니다. Mac OS 9 레트로 스타일.", cat: "MathApplication" },
    age: { name: "나이 계산기 - 만 나이(년/월/일) - 무료 온라인 생일 계산기", desc: "무료 온라인 나이 계산기: 생년월일을 입력하면 만 나이를 년/월/일로 정확하게 계산합니다. 총 일수, 태어난 요일, 다음 생일까지 남은 날짜도 함께 확인하세요. 윤년 자동 처리.", cat: "UtilitiesApplication" },
    grade: { name: "성적 계산기 - GPA 계산기 - 무료 온라인 등급 계산기", desc: "무료 성적 계산기: 과목별 점수와 가중치를 입력하여 평균 점수, GPA(4.0 기준), 등급(A/B/C/D/F)을 계산합니다. 학생들의 학업 성적 추적에 완벽한 도구입니다. Mac OS 9 레트로 스타일.", cat: "EducationApplication" },
    duration: { name: "시간 계산기 - 두 날짜/시간 사이의 시간 차이 계산", desc: "무료 온라인 시간 계산기: 두 날짜와 시간 사이의 정확한 차이를 계산합니다. 년, 일, 시간, 분, 초 단위로 표시. 총 시간, 총 분, 총 초도 함께 확인. 퀵 프리셋: 오늘, 최근 7일, 최근 30일, 최근 1년. Mac OS 9 레트로 스타일.", cat: "UtilitiesApplication" },
    daysuntil: { name: "D-Day 계산기 - 목표 날짜까지 남은 일수", desc: "무료 온라인 D-Day 계산기: 크리스마스, 새해, 생일 등 특정 날짜까지 남은 일, 주, 월, 년을 계산합니다. 요일도 함께 표시. Mac OS 9 레트로 스타일.", cat: "UtilitiesApplication" },
    wordcounter: { name: "글자 수 세기 - 단어 수, 글자 수, 문장 수 세는 프로그램", desc: "무료 온라인 글자 수 세기 도구: 단어 수, 글자 수(공백 포함/제외), 문장 수, 문단 수, 줄 수, 읽기 시간, 말하기 시간을 한 번에 확인. Mac OS 9 레트로 스타일.", cat: "UtilitiesApplication" },
    idealweight: { name: "표준 체중 계산기 - 이상적인 체중 계산 - Devine Hamwi 공식", desc: "무료 온라인 표준 체중 계산기: Devine, Hamwi, Robinson, Miller 공식으로 표준 체중을 계산합니다. 건강한 BMI 체중 범위도 확인. Mac OS 9 레트로 스타일.", cat: "HealthApplication" },
    fuelcost: { name: "기름값 계산기 - 주유비 계산 - 연료비 계산기", desc: "무료 온라인 기름값 계산기: 거리, 연비, 기름값을 입력하여 총 주유비와 L/100km를 계산합니다. 여행 경비 계획에 완벽한 도구. Mac OS 9 레트로 스타일.", cat: "UtilitiesApplication" },
    salary: { name: "연봉 계산기 - 연봉 시급 변환 - 월급 계산기", desc: "무료 온라인 연봉 계산기: 연봉을 시급, 일급, 주급, 격주, 월급으로 변환합니다. 근무 시간과 근무 일수를 설정. Mac OS 9 레트로 스타일.", cat: "FinanceApplication" },
    overtime: { name: "야근 수당 계산기 - 초과 근무 수당 계산", desc: "무료 온라인 야근 수당 계산기: 시급, 정규 시간, 초과 시간을 입력하여 총 임금을 계산합니다. 1.5배, 2배 야근 수당 지원. Mac OS 9 레트로 스타일.", cat: "FinanceApplication" },
    retirement: { name: "은퇴 자금 계산기 - 노후 준비 계산", desc: "무료 온라인 은퇴 자금 계산기: 복리로 은퇴 자금을 예측합니다. 현재 나이, 은퇴 나이, 현재 저축액, 월 납입액 입력. 4% 법칙 표시. Mac OS 9 레트로 스타일.", cat: "FinanceApplication" },
    duedate: { name: "출산 예정일 계산기 - 임신 주수 계산", desc: "무료 온라인 출산 예정일 계산기: Naegele 법칙으로 예정일, 수정일, 현재 주수를 계산합니다. Mac OS 9 레트로 스타일.", cat: "HealthApplication" },
    pace: { name: "페이스 계산기 - 러닝 페이스 계산", desc: "무료 온라인 러닝 페이스 계산기: 페이스, 속도, 시간, 거리 중 두 값을 입력하면 나머지를 계산합니다. 마라톤 트레이닝에 완벽. Mac OS 9 레트로 스타일.", cat: "HealthApplication" },
    sip: { name: "SIP 계산기 - 적립식 투자 계산", desc: "무료 온라인 SIP 계산기: 적립식 투자의 만기 금액을 추정합니다. 월 투자액, 기간, 예상 수익률 입력. Mac OS 9 레트로 스타일.", cat: "FinanceApplication" },
    vat: { name: "부가세 계산기 - VAT 계산기", desc: "무료 온라인 부가세 계산기: 부가세 포함/분리 계산. 10가지 국가별 VAT 세율 지원. 공급가액, 부가세액, 총 금액 표시. Mac OS 9 레트로 스타일.", cat: "FinanceApplication" },
    simpleinterest: { name: "단리 계산기 - 간편 이자 계산기", desc: "무료 온라인 단리 계산기: 원금, 이자율, 기간을 입력하여 이자와 총 금액을 계산합니다. Mac OS 9 레트로 스타일.", cat: "FinanceApplication" },
    period: { name: "생리 주기 계산기 - 월경 주기 계산", desc: "무료 온라인 생리 주기 계산기: 다음 생리일과 배란일을 예측합니다. 생리 주기와 기간 입력. Mac OS 9 레트로 스타일.", cat: "HealthApplication" },
    markup: { name: "마진율 계산기 - 이익률 계산", desc: "무료 온라인 마진율 계산기: 원가와 마진율로 판매가, 이익, 마진율을 계산합니다. Mac OS 9 레트로 스타일.", cat: "FinanceApplication" },
    waterintake: { name: "하루 물 섭취량 계산기", desc: "무료 온라인 하루 물 섭취량 계산기: 체중과 운동량에 따른 하루 물 권장량을 계산합니다. Mac OS 9 레트로 스타일.", cat: "HealthApplication" },
    salestax: { name: "판매세 계산기 - 미국 주별 판매세 계산기", desc: "무료 온라인 미국 판매세 계산기: 미국 50개 주의 판매세를 계산합니다. 가격에 세금 추가 또는 총액에서 세금 제거. 2026년 주별 판매세율 포함. Mac OS 9 레트로 스타일.", cat: "FinanceApplication" },
    petage: { name: "반려동물 나이 계산기 - 개나이 고양이나이 사람나이 변환", desc: "무료 온라인 반려동물 나이 계산기: 개와 고양이의 나이를 사람 나이로 변환합니다. 반려동물의 나이, 품종 크기(소형/중형/대형/초대형), 종을 입력하면 정확한 사람 환산 나이를 알려드립니다. AVMA 수의학 공식 기반. Mac OS 9 레트로 스타일.", cat: "UtilitiesApplication" },
    love: { name: "사랑 계산기 - 이름 궁합 & 별자리 궁합 - 무료 온라인", desc: "무료 온라인 사랑 계산기: 두 사람의 이름과 별자리로 연애 궁합을 계산합니다. 사랑 점수, FLAMES 결과, 별자리 궁합을 한 번에 확인. 친구나 짝꿍과 재미로 공유하세요. Mac OS 9 레트로 스타일.", cat: "EntertainmentApplication" },
    emi: { name: "EMI 계산기 - 대출 월상환액 계산기 - 월 납입금 계산", desc: "무료 온라인 EMI 계산기: 주택담보대출, 자동차대출, 신용대출, 학자금대출의 월 상환액(EMI)을 계산합니다. 대출 금액, 금리, 기간을 입력하면 월 상환액, 총 이자, 총 납입액을 상환 일정표와 함께 보여줍니다. Mac OS 9 레트로 스타일.", cat: "FinanceApplication" },
    sqft: { name: "평방피트 계산기 - 면적 계산기 - 방 면적 계산기", desc: "무료 온라인 평방피트 계산기: 방, 주택 또는 부동산의 면적을 평방피트로 계산합니다. 직사각형, 정사각형, 원형, L자형 방을 지원합니다. 바닥재, 페인트, 타일, 부동산에 완벽합니다. Mac OS 9 레트로 스타일.", cat: "UtilitiesApplication" },
    sleep: { name: "수면 계산기 - 최적 취침 시간 계산 - 개운한 기상", desc: "무료 온라인 수면 계산기: 수면 주기 과학에 기반하여 최적의 취침 및 기상 시간을 찾아줍니다. 90분 수면 주기 기반으로 주기 사이에 가장 개운하게 일어날 수 있는 시간을 계산합니다. Mac OS 9 레트로 스타일.", cat: "HealthApplication" },
  },
  pt: {
    calorie: { name: "Calculadora de Calorias - BMR, TDEE e Macros", desc: "Calculadora de calorias gratuita: calcule BMR, TDEE, IMC e macronutrientes.", cat: "HealthApplication, Nutrition" },
    bmi: { name: "Calculadora de IMC - \u00cdndice de Massa Corporal", desc: "Calculadora de IMC gratuita: calcule seu \u00cdndice de Massa Corporal.", cat: "HealthApplication" },
    convert: { name: "Conversor de Unidades - Comprimento, Peso", desc: "Conversor de unidades gratuito: comprimento, peso, temperatura.", cat: "UtilitiesApplication" },
    date: { name: "Calculadora de Datas - Dias Entre Datas", desc: "Calculadora de datas gratuita: calcule dias entre datas.", cat: "UtilitiesApplication" },
    photo: { name: "Editor de Fotos - Redimensionar, Cortar", desc: "Editor de fotos gratuito: redimensione, corte e comprima.", cat: "MultimediaApplication" },
    qr: { name: "Gerador de C\u00f3digo QR - Criador Gratuito", desc: "Gere c\u00f3digos QR gratuitamente.", cat: "UtilitiesApplication" },
    password: { name: "Gerador de Senhas - Senha Forte Aleat\u00f3ria", desc: "Gere senhas seguras e aleat\u00f3rias.", cat: "SecurityApplication" },
    lotto: { name: "Gerador de N\u00fameros da Loteria", desc: "Gere n\u00fameros de loteria aleat\u00f3rios.", cat: "EntertainmentApplication" },
    percent: { name: "Calculadora de Porcentagem - Gr\u00e1tis Online", desc: "Calculadora de porcentagem gratuita. Calcule X% de Y, X \u00e9 quantos % de Y.", cat: "UtilitiesApplication" },
    currency: { name: "Conversor de Moedas - Calculadora de C\u00e2mbio", desc: "Conversor de moedas gratuito entre 20 moedas principais.", cat: "UtilitiesApplication" },
    random: { name: "Gerador de N\u00fameros Aleat\u00f3rios - Gr\u00e1tis", desc: "Gere n\u00fameros aleat\u00f3rios criptograficamente seguros.", cat: "UtilitiesApplication" },
    text: { name: "Ferramentas de Texto - Contador, Converter, Base64", desc: "Ferramentas de texto gratuitas: contar caracteres, converter mai\u00fasculas/min\u00fasculas, Base64.", cat: "UtilitiesApplication" },
    timer: { name: "Cron\u00f4metro e Temporizador - Cron\u00f4metro Online Gr\u00e1tis", desc: "Cron\u00f4metro online gratuito e temporizador de contagem regressiva com registro de voltas.", cat: "UtilitiesApplication" },
    discount: { name: "Calculadora de Desconto - Calculadora de Desconto Percentual Gr\u00e1tis", desc: "Calculadora de desconto gratuita: calcule o pre\u00e7o final ap\u00f3s o desconto e o valor economizado. Mac OS 9 retro style.", cat: "UtilitiesApplication" },
    loan: { name: "Calculadora de Empr\u00e9stimo - Calculadora de Pagamento de Empr\u00e9stimo Gratuita", desc: "Calculadora de empr\u00e9stimo gratuita: calcule pagamentos mensais, juros totais e amortiza\u00e7\u00e3o para qualquer empr\u00e9stimo. Interface retro Mac OS 9.", cat: "FinanceApplication" },
    compound: { name: "Calculadora de Juros Compostos - Calculadora de Investimento Gratuita", desc: "Calculadora de juros compostos gratuita: veja como seus investimentos crescem com contribui\u00e7\u00f5es mensais. Detalhamento anual, estilo retro Mac OS 9.", cat: "FinanceApplication" },
    mortgage: { name: "Calculadora de Hipoteca - Calculadora de Pagamento de Im\u00f3vel Gratuita", desc: "Calculadora de hipoteca gratuita: calcule pagamentos mensais incluindo principal, juros, impostos e seguro. Tabela de amortiza\u00e7\u00e3o, estilo retro Mac OS 9.", cat: "FinanceApplication" },
    bodyfat: { name: "Calculadora de Gordura Corporal - Calculadora de Percentual de Gordura", desc: "Calculadora de gordura corporal gratuita: estime seu percentual de gordura usando o m\u00e9todo da Marinha dos EUA. Gr\u00e1fico de categorias, estilo retro Mac OS 9.", cat: "HealthApplication" },
    fraction: { name: "Calculadora de Fra\u00e7\u00f5es - Somar, Subtrair, Multiplicar, Dividir Fra\u00e7\u00f5es - Simplificar Fra\u00e7\u00f5es", desc: "Calculadora de fra\u00e7\u00f5es gratuita: somar fra\u00e7\u00f5es, subtrair fra\u00e7\u00f5es, multiplicar fra\u00e7\u00f5es e dividir fra\u00e7\u00f5es. Simplifica resultados para a fra\u00e7\u00e3o irredut\u00edvel. Converte entre fra\u00e7\u00f5es impr\u00f3prias e n\u00fameros mistos. Mostra o equivalente decimal. Ideal para li\u00e7\u00f5es de matem\u00e1tica.", cat: "MathApplication" },
    tip: { name: "Calculadora de Gorjeta - Calculadora de Gratifica\u00e7\u00e3o Gratuita", desc: "Calculadora de gorjeta gratuita: calcule o valor da gorjeta, total da conta e valor por pessoa ao dividir a conta. Escolha 10%, 15%, 18% ou 20% de gorjeta ou insira um percentual personalizado.", cat: "FinanceApplication" },
    average: { name: "Calculadora de M\u00e9dia - Calcular M\u00e9dia, Mediana, Moda - Gr\u00e1tis", desc: "Calculadora de m\u00e9dia gratuita: calcule a m\u00e9dia, mediana e moda de um conjunto de n\u00fameros. Adicione v\u00e1rios n\u00fameros e veja a m\u00e9dia, soma, mediana, amplitude e moda instantaneamente. Estilo retro Mac OS 9.", cat: "MathApplication" },
    age: { name: "Calculadora de Idade - Idade Exata em Anos, Meses, Dias - Calculadora de Anivers\u00e1rio", desc: "Calculadora de idade gratuita: calcule sua idade exata em anos, meses e dias. Informe sua data de nascimento para saber sua idade, dias vividos, dia da semana em que nasceu e dias at\u00e9 seu pr\u00f3ximo anivers\u00e1rio.", cat: "UtilitiesApplication" },
    grade: { name: "Calculadora de Notas - Calculadora GPA - Calculadora de Conceitos", desc: "Calculadora de notas gratuita: adicione disciplinas, notas e pesos para calcular sua nota m\u00e9dia, GPA em escala 4.0 e conceito (A/B/C/D/F). Estilo retro Mac OS 9.", cat: "EducationApplication" },
    duration: { name: "Calculadora de Dura\u00e7\u00e3o de Tempo - Calcular Diferen\u00e7a Entre Datas", desc: "Calculadora de dura\u00e7\u00e3o de tempo gratuita: calcule a diferen\u00e7a exata entre duas datas e horas. Veja a dura\u00e7\u00e3o em anos, dias, horas, minutos e segundos. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    daysuntil: { name: "Calculadora de Dias At\u00e9 - Contagem Regressiva At\u00e9 a Data", desc: "Calculadora de dias at\u00e9 gratuita: descubra quantos dias, semanas, meses e anos faltam para qualquer data alvo. Contagem regressiva para Natal, Ano Novo, anivers\u00e1rio. Mostra o dia da semana. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    wordcounter: { name: "Contador de Palavras - Contagem de Palavras e Caracteres Gratuito", desc: "Contador de palavras gratuito: conte palavras, caracteres (com e sem espa\u00e7os), frases, par\u00e1grafos, linhas, tempo de leitura e fala. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    idealweight: { name: "Calculadora de Peso Ideal - Peso Saud\u00e1vel - F\u00f3rmulas Devine Hamwi", desc: "Calculadora de peso ideal gratuita: calcule seu peso ideal usando as f\u00f3rmulas Devine, Hamwi, Robinson e Miller. Veja a faixa de peso saud\u00e1vel do IMC. Estilo retro Mac OS 9.", cat: "HealthApplication" },
    fuelcost: { name: "Calculadora de Custo de Combust\u00edvel - Estimador de Gastos com Gasolina", desc: "Calculadora de custo de combust\u00edvel gratuita: estime o custo total de combust\u00edvel para qualquer viagem. Insira dist\u00e2ncia, consumo e pre\u00e7o. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    salary: { name: "Calculadora de Sal\u00e1rio - Converter Anual para Por Hora", desc: "Calculadora de sal\u00e1rio gratuita: converta sal\u00e1rio anual em pagamento por hora, dia, semana, quinzena e m\u00eas. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    overtime: { name: "Calculadora de Horas Extras - Pagamento de Horas Extras", desc: "Calculadora de horas extras gratuita: calcule o pagamento de horas extras com tarifa 1.5x e 2x. Insira tarifa por hora, horas regulares e horas extras. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    retirement: { name: "Calculadora de Aposentadoria - Planejador de Aposentadoria", desc: "Calculadora de aposentadoria gratuita: estime sua poupan\u00e7a para a aposentadoria com proje\u00e7\u00f5es de juros compostos. Mostra a regra de retirada segura de 4%. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    duedate: { name: "Calculadora de Data Prevista - Gravidez", desc: "Calculadora de data prevista gratuita: calcule sua data prov\u00e1vel do parto, data da concep\u00e7\u00e3o e semana atual de gravidez usando a regra de Naegele. Estilo retro Mac OS 9.", cat: "HealthApplication" },
    pace: { name: "Calculadora de Ritmo - Ritmo de Corrida", desc: "Calculadora de ritmo gratuita para corredores: calcule ritmo (min/km), velocidade (km/h), tempo ou dist\u00e2ncia. Perfeita para treinamento de maratona. Estilo retro Mac OS 9.", cat: "HealthApplication" },
    sip: { name: "Calculadora SIP - Plano de Investimento Sistem\u00e1tico", desc: "Calculadora SIP gratuita: estime o valor de vencimento do seu plano de investimento sistem\u00e1tico. Insira investimento mensal, prazo e retorno esperado. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    salestax: { name: "Calculadora de Imposto sobre Vendas - Imposto Estadual EUA", desc: "Calculadora de imposto sobre vendas gratuita: calcule o imposto sobre vendas para qualquer estado dos EUA. Adicione ou remova imposto de um pre\u00e7o. Inclui taxas de 2026 para todos os 50 estados. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    petage: { name: "Calculadora de Idade de Animais - Idade de C\u00e3es e Gatos em Anos Humanos", desc: "Calculadora gratuita de idade de animais de estima\u00e7\u00e3o: converta anos de c\u00e3es e gatos em anos humanos. Insira a idade, porte (pequeno, m\u00e9dio, grande, gigante) e esp\u00e9cie. Usa f\u00f3rmulas veterin\u00e1rias AVMA. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    love: { name: "Calculadora de Amor - Compatibilidade de Nomes e Zod\u00edaco", desc: "Calculadora de amor gratuita: calcule a compatibilidade amorosa entre dois nomes e signos do zod\u00edaco. Obtenha sua porcentagem de amor, resultado FLAMES e pontua\u00e7\u00e3o zodiacal. Estilo retro Mac OS 9.", cat: "EntertainmentApplication" },
    emi: { name: "Calculadora de EMI - Parcela Mensal de Empr\u00e9stimo - Calculadora de Pagamento Mensal", desc: "Calculadora de EMI gratuita: calcule sua parcela mensal (EMI) para empr\u00e9stimos imobili\u00e1rios, de carro, pessoais e estudantis. Insira valor, taxa e prazo. Mostra tabela de amortiza\u00e7\u00e3o. Estilo retro Mac OS 9.", cat: "FinanceApplication" },
    sqft: { name: "Calculadora de Metragem Quadrada - Calculadora de \u00c1rea de C\u00f4modo", desc: "Calculadora de metragem quadrada gratuita: calcule a \u00e1rea de qualquer c\u00f4modo, casa ou propriedade em p\u00e9s quadrados. Suporta ret\u00e2ngulo, quadrado, c\u00edrculo e formato L. Estilo retro Mac OS 9.", cat: "UtilitiesApplication" },
    sleep: { name: "Calculadora de Sono - Melhor Hor\u00e1rio para Dormir - Acordar Descansado", desc: "Calculadora de sono gratuita: encontre o melhor hor\u00e1rio para dormir e acordar usando a ci\u00eancia do ciclo do sono. Baseada em ciclos de 90 minutos. Estilo retro Mac OS 9.", cat: "HealthApplication" },
  }
};

function getToolKey(pathname) {
  if (!pathname) return 'calorie';
  const p = pathname.replace(/^\/[a-z]{2}(\/|$)/, '/').replace(/\/$/, '');
  const toolMap = { '/bmi': 'bmi', '/convert': 'convert', '/date': 'date', '/photo': 'photo', '/qr': 'qr', '/password': 'password', '/lotto': 'lotto', '/percent': 'percent', '/currency': 'currency', '/random': 'random', '/text': 'text', '/timer': 'timer', '/discount': 'discount', '/loan': 'loan', '/compound': 'compound', '/mortgage': 'mortgage', '/bodyfat': 'bodyfat', '/fraction': 'fraction', '/tip': 'tip', '/average': 'average', '/age': 'age', '/grade': 'grade', '/duration': 'duration', '/daysuntil': 'daysuntil', '/wordcounter': 'wordcounter', '/idealweight': 'idealweight', '/fuelcost': 'fuelcost', '/salary': 'salary', '/overtime': 'overtime', '/retirement': 'retirement', '/duedate': 'duedate', '/pace': 'pace', '/sip': 'sip', '/vat': 'vat', '/simpleinterest': 'simpleinterest', '/period': 'period', '/markup': 'markup', '/waterintake': 'waterintake', '/salestax': 'salestax', '/petage': 'petage', '/love': 'love', '/emi': 'emi', '/sqft': 'sqft', '/sleep': 'sleep' };
  return toolMap[p] || 'calorie';
}

export default async function LocaleLayout({ children, params }) {
  const { locale } = await params;
  const headersList = await headers();
  const pathname = headersList.get('x-pathname') || headersList.get('x-url') || '';
  const toolKey = getToolKey(pathname);
  const t = tools[locale] || tools.en;
  const tool = t[toolKey] || t.calorie;

  const schemaJson = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: tool.name,
    description: tool.desc,
    applicationCategory: tool.cat,
    operatingSystem: "Web",
    browserRequirements: "Requires JavaScript",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
    author: {
      "@type": "Organization",
      name: "hello-tools",
      url: "https://oxoxox1.com",
    },
  });

  return (
    <html lang={locale} className="h-full antialiased">
      <head>
        <title>{tool.name}</title>
        <meta name="description" content={tool.desc} />
        <meta property="og:title" content={tool.name} />
        <meta property="og:description" content={tool.desc} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={`https://oxoxox1.com/${locale}${pathname.replace(/^\/[a-z]{2}/, '')}`} />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={tool.name} />
        <meta name="twitter:description" content={tool.desc} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: schemaJson }}
          suppressHydrationWarning
        />
        {/* Google AdSense Auto Ads */}
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8178172082493004"
          crossOrigin="anonymous"></script>
      </head>
      <body className="min-h-full flex flex-col" style={{ background: 'var(--os9-bg)' }}>
        {children}

        {/* SEO Content Section — visible text for Google AdSense crawling */}
        <div className="mt-6 px-2" style={{ maxWidth: 520, width: '100%', margin: '0 auto' }}>
          <article className="text-xs leading-relaxed" style={{ opacity: 0.75, lineHeight: 1.7 }}>
            <h2 className="text-sm font-bold mb-2">{tool.name}</h2>
            <p className="mb-3">{tool.desc}</p>
            <p className="mb-2">
              {locale === 'ko' ? `무료 온라인 ${toolKey === 'calorie' ? '도구 모음' : '도구'}입니다. ` :
               locale === 'zh' ? `免费在线${toolKey === 'calorie' ? '工具集' : '工具'}。` :
               locale === 'es' ? `Herramienta en línea gratuita. ` :
               locale === 'pt' ? `Ferramenta online gratuita. ` :
               `Free online tool. `}
              {locale === 'ko' ? 'hello-tools는 누구나 쉽게 사용할 수 있는 무료 웹 도구를 제공합니다. 계산기, 변환기, 생성기 등 다양한 도구를 Mac OS 9 레트로 스타일로 만나보세요.' :
               locale === 'zh' ? 'hello-tools 提供免费在线工具，包括计算器、转换器、生成器等。所有工具均采用 Mac OS 9 复古风格设计。' :
               locale === 'es' ? 'hello-tools ofrece herramientas web gratuitas y fáciles de usar. Calculadoras, convertidores, generadores y más, con estilo retro Mac OS 9.' :
               locale === 'pt' ? 'hello-tools oferece ferramentas web gratuitas e fáceis de usar. Calculadoras, conversores, geradores e mais, com estilo retro Mac OS 9.' :
               `hello-tools offers free, easy-to-use web tools. Calculators, converters, generators, and more — all in Mac OS 9 retro style. No signup required, no data stored.`}
            </p>
          </article>
        </div>

        <Analytics />
      </body>
    </html>
  );
}